// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7f4cbde497b625c3 "Cowork Agent-Build", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
 * smoothScroll?: boolean // Smooth Scroll
}} Props

 */
import { routes } from "./chunks/chunk-E76XYZGR.js";

// virtual:button-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7A4KnY5ot0bZtmwoMdrW/9XhCuqbZVI6EV5OtUveO/JAwING_1A.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	oUe7eXjW7: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"oUe7eXjW7",
	"Q3Mho9xIy",
	"KGj67djXx",
	"UjblguRPj",
	"csqsQMeCK",
];
var serializationHash = "framer-YV4jQ";
var variantClassNames = {
	csqsQMeCK: "framer-v-m0ru1f",
	KGj67djXx: "framer-v-1j4aumr",
	oUe7eXjW7: "framer-v-xw6qz8",
	Q3Mho9xIy: "framer-v-dzh9s1",
	UjblguRPj: "framer-v-jln2b6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "oUe7eXjW7",
	Disabled: "KGj67djXx",
	Error: "csqsQMeCK",
	Loading: "Q3Mho9xIy",
	Success: "UjblguRPj",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, smoothScroll, width, ...props }) => {
	return {
		...props,
		mnlmbwaMj: smoothScroll ?? props.mnlmbwaMj ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "oUe7eXjW7",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		mnlmbwaMj: mnlmbwaMj2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "oUe7eXjW7",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "Q3Mho9xIy") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "Q3Mho9xIy") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={"#how-it-works"}
						motionChild={true}
						nodeId={"oUe7eXjW7"}
						openInNewTab={false}
						scopeId={"JAwING_1A"}
						smoothScroll={mnlmbwaMj2}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-xw6qz8", className, classNames)} framer-1yd6b49`}
							data-framer-name={"Default"}
							data-reset={"button"}
							layoutDependency={layoutDependency}
							layoutId={"oUe7eXjW7"}
							ref={refBinding}
							style={{
								background:
									"linear-gradient(180deg, rgb(250, 204, 21) 0%, rgb(250, 204, 21) 100%)",
								backgroundColor: "rgb(250, 204, 21)",
								borderBottomLeftRadius: 3,
								borderBottomRightRadius: 3,
								borderTopLeftRadius: 3,
								borderTopRightRadius: 3,
								opacity: 1,
								...style,
							}}
							variants={{
								"oUe7eXjW7-hover": {
									background:
										"linear-gradient(180deg, rgb(250, 204, 21) -72%, rgb(255, 18, 18) 188%)",
									backgroundColor: "rgba(0, 0, 0, 0)",
									opacity: 1,
								},
								"oUe7eXjW7-pressed": {
									background:
										"linear-gradient(180deg, rgb(51, 51, 51) 0%, rgb(51, 51, 51) 100%)",
									backgroundColor: "rgb(51, 51, 51)",
									opacity: 1,
								},
								csqsQMeCK: {
									background:
										"linear-gradient(180deg, rgba(255, 34, 68, 0.15) 0%, rgba(255, 34, 68, 0.15) 100%)",
									backgroundColor: "rgba(255, 34, 68, 0.15)",
									opacity: 1,
								},
								KGj67djXx: {
									opacity: 0.5,
								},
								UjblguRPj: {
									opacity: 1,
								},
							}}
							{...addPropertyOverrides(
								{
									"oUe7eXjW7-hover": {
										"data-framer-name": void 0,
									},
									"oUe7eXjW7-pressed": {
										"data-framer-name": void 0,
									},
									csqsQMeCK: {
										"data-framer-name": "Error",
									},
									KGj67djXx: {
										"data-framer-name": "Disabled",
									},
									Q3Mho9xIy: {
										"data-framer-name": "Loading",
									},
									UjblguRPj: {
										"data-framer-name": "Success",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{isDisplayed() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-13yz4rq"}
									fonts={["FS;Manrope-extrabold"]}
									layoutDependency={layoutDependency}
									layoutId={"IUuSgP82i"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-af175f08-5ee8-489b-8b25-c4cbf6600058, rgb(13, 17, 22))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									variants={{
										csqsQMeCK: {
											"--extracted-r6o4lv": "rgb(255, 34, 68)",
										},
										UjblguRPj: {
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											csqsQMeCK: {
												children: (
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-size": "14px",
																"--framer-font-weight": "600",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 34, 68))",
															}}
														>
															{"Something went wrong"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-SemiBold"],
											},
											UjblguRPj: {
												children: (
													<React.Fragment>
														<motion.p
															dir={"auto"}
															style={{
																"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
																"--framer-font-size": "14px",
																"--framer-font-weight": "600",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Thank you"}
														</motion.p>
													</React.Fragment>
												),
												fonts: ["Inter-SemiBold"],
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											dir={"auto"}
											style={{
												"--font-selector": "RlM7TWFucm9wZS1leHRyYWJvbGQ=",
												"--framer-font-family":
													'"Manrope", "Manrope Placeholder", sans-serif',
												"--framer-font-size": "20px",
												"--framer-font-weight": "800",
												"--framer-letter-spacing": "0.12em",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-af175f08-5ee8-489b-8b25-c4cbf6600058, rgb(13, 17, 22)))",
											}}
										>
											{"HOW IT WORKS"}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
							{isDisplayed1() && (
								<motion.div
									className={"framer-15ci2bl"}
									data-framer-name={"Spinner"}
									layoutDependency={layoutDependency}
									layoutId={"RQI2HxTUb"}
									style={{
										mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										WebkitMask:
											"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									}}
								>
									<MotionDivWithFX
										__framer__loop={animation}
										__framer__loopEffectEnabled={true}
										__framer__loopRepeatDelay={0}
										__framer__loopRepeatType={"loop"}
										__framer__loopTransition={transition2}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-137uy10"}
										data-framer-name={"Conic"}
										layoutDependency={layoutDependency}
										layoutId={"bSLbAlFhL"}
										style={{
											background:
												"conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
											backgroundColor: "rgb(68, 204, 255)",
											mask: "none",
											WebkitMask: "none",
										}}
										variants={{
											Q3Mho9xIy: {
												background:
													"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
												backgroundColor: "rgba(0, 0, 0, 0)",
												mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
												WebkitMask:
													"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											},
										}}
									>
										<motion.div
											className={"framer-zloq9u"}
											data-framer-name={"Rounding"}
											layoutDependency={layoutDependency}
											layoutId={"GoFcTW3Kt"}
											style={{
												backgroundColor: "rgb(255, 255, 255)",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
											transformTemplate={transformTemplate1}
										/>
									</MotionDivWithFX>
								</motion.div>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YV4jQ.framer-1yd6b49, .framer-YV4jQ .framer-1yd6b49 { display: block; }",
	".framer-YV4jQ.framer-xw6qz8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 58px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 240px; }",
	".framer-YV4jQ .framer-13yz4rq { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-YV4jQ .framer-15ci2bl { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-YV4jQ .framer-137uy10 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-YV4jQ .framer-zloq9u { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-YV4jQ.framer-v-dzh9s1.framer-xw6qz8, .framer-YV4jQ.framer-v-1j4aumr.framer-xw6qz8, .framer-YV4jQ.framer-v-jln2b6.framer-xw6qz8, .framer-YV4jQ.framer-v-m0ru1f.framer-xw6qz8 { cursor: unset; }",
	".framer-YV4jQ.framer-v-dzh9s1 .framer-137uy10 { overflow: hidden; }",
];
var FramerJAwING_1A = withCSS(Component, css, "framer-YV4jQ");
var stdin_default = FramerJAwING_1A;
FramerJAwING_1A.displayName = "Button 2";
FramerJAwING_1A.defaultProps = {
	height: 58,
	width: 240,
};
addPropertyControls(FramerJAwING_1A, {
	variant: {
		options: ["oUe7eXjW7", "Q3Mho9xIy", "KGj67djXx", "UjblguRPj", "csqsQMeCK"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
	mnlmbwaMj: {
		defaultValue: true,
		title: "Smooth Scroll",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerJAwING_1A,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Manrope",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Manrope",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/7EWHG4AMROQSXDCQTDPGBVASATB7CED2/TJSQTK5FHJ2MYKML5IXF2G6YTGFJLTYL/K4ZMLVLHYIFVTTTWGVOTVGOFUUX7NVGI.woff2",
					weight: "800",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "oUe7eXjW7",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Button2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_2_default = ComponentWithRoot;
export { button_2_default as default };
