// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7f4cbde497b625c3 "Cowork Agent-Build", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
 * title?: string // Title
}} Props

 */
import { routes } from "./chunks/chunk-E76XYZGR.js";

// virtual:cta
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iKbCrwUHNGmj2pIQu4ek/QwTGmsK9ssuIW6rlkSUg/hIhiTJE9H.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	hBtvow_gx: {
		hover: true,
	},
};
var serializationHash = "framer-VlwFG";
var variantClassNames = {
	hBtvow_gx: "framer-v-1sehrag",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		sjweCVENK: title ?? props.sjweCVENK ?? "Join the Bootcamp",
		tLKc9FrRm: link ?? props.tLKc9FrRm,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		tLKc9FrRm: tLKc9FrRm2,
		sjweCVENK: sjweCVENK2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "hBtvow_gx",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={tLKc9FrRm2}
						motionChild={true}
						nodeId={"hBtvow_gx"}
						openInNewTab={true}
						scopeId={"hIhiTJE9H"}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1sehrag", className, classNames)} framer-io7720`}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"hBtvow_gx"}
							ref={refBinding}
							style={{
								background:
									"linear-gradient(180deg, rgb(250, 204, 21) 0%, rgb(250, 204, 21) 100%)",
								backgroundColor: "rgb(250, 204, 21)",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								...style,
							}}
							variants={{
								"hBtvow_gx-hover": {
									background:
										"linear-gradient(180deg, rgb(244, 210, 53) -114.00000000000001%, rgb(255, 18, 18) 200%)",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
							}}
							{...addPropertyOverrides(
								{
									"hBtvow_gx-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1963r3"}
								data-framer-name={"Subtitle"}
								fonts={["GF;Manrope-800"]}
								layoutDependency={layoutDependency}
								layoutId={"kCsaIUj3d"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={sjweCVENK2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										dir={"auto"}
										style={{
											"--font-selector": "R0Y7TWFucm9wZS04MDA=",
											"--framer-font-family":
												'"Manrope", "Manrope Placeholder", sans-serif',
											"--framer-font-size": "20px",
											"--framer-font-weight": "800",
											"--framer-letter-spacing": "0.05em",
											"--framer-line-height": "150%",
											"--framer-text-alignment": "center",
											"--framer-text-transform": "uppercase",
										}}
									>
										{"Join the Bootcamp"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-VlwFG.framer-io7720, .framer-VlwFG .framer-io7720 { display: block; }",
	".framer-VlwFG.framer-1sehrag { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 14px 32px 14px 32px; position: relative; text-decoration: none; width: 287px; }",
	".framer-VlwFG .framer-1963r3 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
];
var FramerhIhiTJE9H = withCSS(Component, css, "framer-VlwFG");
var stdin_default = FramerhIhiTJE9H;
FramerhIhiTJE9H.displayName = "cta";
FramerhIhiTJE9H.defaultProps = {
	height: 58,
	width: 287,
};
addPropertyControls(FramerhIhiTJE9H, {
	tLKc9FrRm: {
		title: "Link",
		type: ControlType.Link,
	},
	sjweCVENK: {
		defaultValue: "Join the Bootcamp",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerhIhiTJE9H,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Manrope",
					source: "google",
					style: "normal",
					uiFamilyName: "Manrope",
					url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk59E-_A87jxeN7B.woff2",
					weight: "800",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var cta_default = ComponentWithRoot;
export { cta_default as default };
