// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7f4cbde497b625c3 "Cowork Agent-Build", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'open' | 'close' // Variant
 * title?: string // Title
 * copy?: string // copy
 * tap?: Function // Tap
}} Props

 */
import { routes } from "./chunks/chunk-E76XYZGR.js";

// virtual:faq-comp
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ePNqXOTNV5DKOouct5h3/6kLjGRFHQzXNDdZ2X0zd/u6zq08eRU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["lfpAgYSek", "HDQgyRxge"];
var serializationHash = "framer-EA2bg";
var variantClassNames = {
	HDQgyRxge: "framer-v-1k35m0z",
	lfpAgYSek: "framer-v-1mtcnxq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	close: "HDQgyRxge",
	open: "lfpAgYSek",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ copy, height, id, tap, title, width, ...props }) => {
	return {
		...props,
		fWTlhIRKu: tap ?? props.fWTlhIRKu,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lfpAgYSek",
		YTCIaj6tN: title ?? props.YTCIaj6tN ?? "Mergers and Acquisitions",
		zBMHYX5iv:
			copy ??
			props.zBMHYX5iv ??
			"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		YTCIaj6tN: YTCIaj6tN2,
		zBMHYX5iv: zBMHYX5iv2,
		fWTlhIRKu: fWTlhIRKu2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lfpAgYSek",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapb57xh7 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fWTlhIRKu2) {
			const res = await fWTlhIRKu2(...args);
			if (res === false) return false;
		}
	});
	const onTap10u0ej8 = activeVariantCallback(async (...args) => {
		setVariant("HDQgyRxge");
	});
	const onTapdp0lmy = activeVariantCallback(async (...args) => {
		setVariant("lfpAgYSek");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "HDQgyRxge") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1mtcnxq",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"lfpAgYSek"}
						onTap={onTapb57xh7}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-31744b1b-12e2-43fa-883d-5c5630fea3a8, rgb(59, 61, 58))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-00686d87-f2b5-4f40-80f3-9367a9ef324d, rgb(15, 21, 28))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
						variants={{
							HDQgyRxge: {
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							},
						}}
						{...addPropertyOverrides(
							{
								HDQgyRxge: {
									"data-framer-name": "close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1i5adlm"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"XZ4l3QUQb"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-2no77j"}
								data-framer-name={"Mergers and Acquisitions"}
								fonts={["FS;Manrope-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"p2ePrAmS9"}
								style={{
									"--extracted-1eung3n":
										"var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={YTCIaj6tN2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										dir={"auto"}
										style={{
											"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
											"--framer-font-family":
												'"Manrope", "Manrope Placeholder", sans-serif',
											"--framer-font-size": "18px",
											"--framer-line-height": "120%",
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205)))",
										}}
									>
										{"Mergers and Acquisitions"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-w3sm7f"}
								data-framer-name={"icon"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"orfoNcTyz"}
								onTap={onTap10u0ej8}
								{...addPropertyOverrides(
									{
										HDQgyRxge: {
											onTap: onTapdp0lmy,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion.div
									className={"framer-u17kfv"}
									layoutDependency={layoutDependency}
									layoutId={"jxboIUMag"}
									style={{
										backgroundColor:
											"var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205))",
										borderBottomLeftRadius: 2,
										borderBottomRightRadius: 2,
										borderTopLeftRadius: 2,
										borderTopRightRadius: 2,
										rotate: 45,
									}}
									variants={{
										HDQgyRxge: {
											rotate: 0,
										},
									}}
								/>
								<motion.div
									className={"framer-1rstu3i"}
									layoutDependency={layoutDependency}
									layoutId={"mpCnao7qb"}
									style={{
										backgroundColor:
											"var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205))",
										borderBottomLeftRadius: 2,
										borderBottomRightRadius: 2,
										borderTopLeftRadius: 2,
										borderTopRightRadius: 2,
										rotate: 45,
									}}
									variants={{
										HDQgyRxge: {
											rotate: 0,
										},
									}}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1eec8o1"}
								data-framer-name={"Description"}
								layoutDependency={layoutDependency}
								layoutId={"l5v2R2zLd"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-el25qv"}
									data-framer-name={
										"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more."
									}
									fonts={["FS;Manrope-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"fmivZAQQO"}
									style={{
										"--extracted-r6o4lv": "rgba(241, 238, 205, 0.7)",
										"--framer-paragraph-spacing": "0px",
									}}
									text={zBMHYX5iv2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											dir={"auto"}
											style={{
												"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
												"--framer-font-family":
													'"Manrope", "Manrope Placeholder", sans-serif',
												"--framer-line-height": "150%",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgba(241, 238, 205, 0.7))",
											}}
										>
											{
												"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EA2bg.framer-4g4pg1, .framer-EA2bg .framer-4g4pg1 { display: block; }",
	".framer-EA2bg.framer-1mtcnxq { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px; position: relative; width: 736px; }",
	".framer-EA2bg .framer-1i5adlm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-EA2bg .framer-2no77j, .framer-EA2bg .framer-el25qv { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-EA2bg .framer-w3sm7f { aspect-ratio: 1 / 1; cursor: pointer; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: hidden; position: relative; width: 32px; }",
	".framer-EA2bg .framer-u17kfv { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 18px; will-change: var(--framer-will-change-override, transform); }",
	".framer-EA2bg .framer-1rstu3i { flex: none; height: 18px; left: calc(50.00000000000002% - 2px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 18px / 2); width: 2px; will-change: var(--framer-will-change-override, transform); }",
	".framer-EA2bg .framer-1eec8o1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	'.framer-EA2bg[data-border="true"]::after, .framer-EA2bg [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Frameru6zq08eRU = withCSS(Component, css, "framer-EA2bg");
var stdin_default = Frameru6zq08eRU;
Frameru6zq08eRU.displayName = "faq-comp";
Frameru6zq08eRU.defaultProps = {
	height: 140,
	width: 736,
};
addPropertyControls(Frameru6zq08eRU, {
	variant: {
		options: ["lfpAgYSek", "HDQgyRxge"],
		optionTitles: ["open", "close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	YTCIaj6tN: {
		defaultValue: "Mergers and Acquisitions",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	zBMHYX5iv: {
		defaultValue:
			"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more.",
		displayTextArea: true,
		title: "copy",
		type: ControlType.String,
	},
	fWTlhIRKu: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Frameru6zq08eRU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Manrope",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Manrope",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/2TYFCBHUANEXS6QGR5EQDUNAFH6LSWM3/AYNOU3VEA4LRTDNKJQUFNVNUTYSGOUOP/UXO4O7K2G3HI3D2VKD7UXVJVJD26P4BQ.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-comp
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "HDQgyRxge",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqCompFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var faq_comp_default = ComponentWithRoot;
export { faq_comp_default as default };
