// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7f4cbde497b625c3 "Cowork Agent-Build", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' | 'Variant 5' | 'Variant 6' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-E76XYZGR.js";

// virtual:faq-main
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7VJGtBGqw7e35VllQ6JM/2OngfZESHx0dzrI1QOhj/v8UHvsoJG.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/boO8OulfrcNeQZ4ioyT5/BqBGPuIYMzkkK3zKOB3a/u6zq08eRU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["lfpAgYSek", "HDQgyRxge"];
var serializationHash = "framer-EA2bg";
var variantClassNames = {
	HDQgyRxge: "framer-v-1k35m0z",
	lfpAgYSek: "framer-v-1mtcnxq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	close: "HDQgyRxge",
	open: "lfpAgYSek",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ copy, height, id, tap, title, width, ...props }) => {
	return {
		...props,
		fWTlhIRKu: tap ?? props.fWTlhIRKu,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "lfpAgYSek",
		YTCIaj6tN: title ?? props.YTCIaj6tN ?? "Mergers and Acquisitions",
		zBMHYX5iv:
			copy ??
			props.zBMHYX5iv ??
			"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		YTCIaj6tN: YTCIaj6tN2,
		zBMHYX5iv: zBMHYX5iv2,
		fWTlhIRKu: fWTlhIRKu2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lfpAgYSek",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapb57xh7 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (fWTlhIRKu2) {
			const res = await fWTlhIRKu2(...args);
			if (res === false) return false;
		}
	});
	const onTap10u0ej8 = activeVariantCallback(async (...args) => {
		setVariant("HDQgyRxge");
	});
	const onTapdp0lmy = activeVariantCallback(async (...args) => {
		setVariant("lfpAgYSek");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "HDQgyRxge") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1mtcnxq",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"lfpAgYSek"}
						onTap={onTapb57xh7}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-31744b1b-12e2-43fa-883d-5c5630fea3a8, rgb(59, 61, 58))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-00686d87-f2b5-4f40-80f3-9367a9ef324d, rgb(15, 21, 28))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
						variants={{
							HDQgyRxge: {
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
							},
						}}
						{...addPropertyOverrides(
							{
								HDQgyRxge: {
									"data-framer-name": "close",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1i5adlm"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"XZ4l3QUQb"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-2no77j"}
								data-framer-name={"Mergers and Acquisitions"}
								fonts={["FS;Manrope-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"p2ePrAmS9"}
								style={{
									"--extracted-1eung3n":
										"var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={YTCIaj6tN2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										dir={"auto"}
										style={{
											"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
											"--framer-font-family":
												'"Manrope", "Manrope Placeholder", sans-serif',
											"--framer-font-size": "18px",
											"--framer-line-height": "120%",
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205)))",
										}}
									>
										{"Mergers and Acquisitions"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-w3sm7f"}
								data-framer-name={"icon"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"orfoNcTyz"}
								onTap={onTap10u0ej8}
								{...addPropertyOverrides(
									{
										HDQgyRxge: {
											onTap: onTapdp0lmy,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion.div
									className={"framer-u17kfv"}
									layoutDependency={layoutDependency}
									layoutId={"jxboIUMag"}
									style={{
										backgroundColor:
											"var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205))",
										borderBottomLeftRadius: 2,
										borderBottomRightRadius: 2,
										borderTopLeftRadius: 2,
										borderTopRightRadius: 2,
										rotate: 45,
									}}
									variants={{
										HDQgyRxge: {
											rotate: 0,
										},
									}}
								/>
								<motion.div
									className={"framer-1rstu3i"}
									layoutDependency={layoutDependency}
									layoutId={"mpCnao7qb"}
									style={{
										backgroundColor:
											"var(--token-edf4f92b-5f81-4edd-8325-6e2b32a50c2b, rgb(241, 238, 205))",
										borderBottomLeftRadius: 2,
										borderBottomRightRadius: 2,
										borderTopLeftRadius: 2,
										borderTopRightRadius: 2,
										rotate: 45,
									}}
									variants={{
										HDQgyRxge: {
											rotate: 0,
										},
									}}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1eec8o1"}
								data-framer-name={"Description"}
								layoutDependency={layoutDependency}
								layoutId={"l5v2R2zLd"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-el25qv"}
									data-framer-name={
										"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more."
									}
									fonts={["FS;Manrope-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"fmivZAQQO"}
									style={{
										"--extracted-r6o4lv": "rgba(241, 238, 205, 0.7)",
										"--framer-paragraph-spacing": "0px",
									}}
									text={zBMHYX5iv2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											dir={"auto"}
											style={{
												"--font-selector": "RlM7TWFucm9wZS1yZWd1bGFy",
												"--framer-font-family":
													'"Manrope", "Manrope Placeholder", sans-serif',
												"--framer-line-height": "150%",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgba(241, 238, 205, 0.7))",
											}}
										>
											{
												"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EA2bg.framer-4g4pg1, .framer-EA2bg .framer-4g4pg1 { display: block; }",
	".framer-EA2bg.framer-1mtcnxq { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 24px; position: relative; width: 736px; }",
	".framer-EA2bg .framer-1i5adlm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-EA2bg .framer-2no77j, .framer-EA2bg .framer-el25qv { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-EA2bg .framer-w3sm7f { aspect-ratio: 1 / 1; cursor: pointer; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: hidden; position: relative; width: 32px; }",
	".framer-EA2bg .framer-u17kfv { flex: none; height: 2px; left: calc(50.00000000000002% - 18px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 18px; will-change: var(--framer-will-change-override, transform); }",
	".framer-EA2bg .framer-1rstu3i { flex: none; height: 18px; left: calc(50.00000000000002% - 2px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 18px / 2); width: 2px; will-change: var(--framer-will-change-override, transform); }",
	".framer-EA2bg .framer-1eec8o1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	'.framer-EA2bg[data-border="true"]::after, .framer-EA2bg [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Frameru6zq08eRU = withCSS(Component, css, "framer-EA2bg");
var stdin_default = Frameru6zq08eRU;
Frameru6zq08eRU.displayName = "faq-comp";
Frameru6zq08eRU.defaultProps = {
	height: 140,
	width: 736,
};
addPropertyControls(Frameru6zq08eRU, {
	variant: {
		options: ["lfpAgYSek", "HDQgyRxge"],
		optionTitles: ["open", "close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	YTCIaj6tN: {
		defaultValue: "Mergers and Acquisitions",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	zBMHYX5iv: {
		defaultValue:
			"At Advocare, we handle a wide range of legal matters, including corporate law, intellectual property rights, employment law, real estate law, litigation, and more.",
		displayTextArea: true,
		title: "copy",
		type: ControlType.String,
	},
	fWTlhIRKu: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Frameru6zq08eRU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Manrope",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Manrope",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/2TYFCBHUANEXS6QGR5EQDUNAFH6LSWM3/AYNOU3VEA4LRTDNKJQUFNVNUTYSGOUOP/UXO4O7K2G3HI3D2VKD7UXVJVJD26P4BQ.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/7VJGtBGqw7e35VllQ6JM/2OngfZESHx0dzrI1QOhj/v8UHvsoJG.js
var FaqCompFonts = getFonts(stdin_default);
var cycleOrder2 = [
	"N6y2PsIAC",
	"YSJjBxE6e",
	"CscMDZeaw",
	"w_Hgj1z0m",
	"vIzlDr2lQ",
	"EYGZGvkqn",
];
var serializationHash2 = "framer-8GVlV";
var variantClassNames2 = {
	CscMDZeaw: "framer-v-118o8rz",
	EYGZGvkqn: "framer-v-68qwfv",
	N6y2PsIAC: "framer-v-30jryl",
	vIzlDr2lQ: "framer-v-1in0aap",
	w_Hgj1z0m: "framer-v-1l8d78c",
	YSJjBxE6e: "framer-v-ydik9w",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap2 = {
	"Variant 1": "N6y2PsIAC",
	"Variant 2": "YSJjBxE6e",
	"Variant 3": "CscMDZeaw",
	"Variant 4": "w_Hgj1z0m",
	"Variant 5": "vIzlDr2lQ",
	"Variant 6": "EYGZGvkqn",
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "N6y2PsIAC",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "N6y2PsIAC",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const fWTlhIRKuqipfw6 = activeVariantCallback(async (...args) => {
		setVariant("N6y2PsIAC");
	});
	const fWTlhIRKu434jgf = activeVariantCallback(async (...args) => {
		setVariant("YSJjBxE6e");
	});
	const fWTlhIRKum44pyu = activeVariantCallback(async (...args) => {
		setVariant("CscMDZeaw");
	});
	const fWTlhIRKue0d5q8 = activeVariantCallback(async (...args) => {
		setVariant("w_Hgj1z0m");
	});
	const fWTlhIRKu1hcwi60 = activeVariantCallback(async (...args) => {
		setVariant("vIzlDr2lQ");
	});
	const fWTlhIRKulnq9nu = activeVariantCallback(async (...args) => {
		setVariant("EYGZGvkqn");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-30jryl",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"N6y2PsIAC"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								CscMDZeaw: {
									"data-framer-name": "Variant 3",
								},
								EYGZGvkqn: {
									"data-framer-name": "Variant 6",
								},
								vIzlDr2lQ: {
									"data-framer-name": "Variant 5",
								},
								w_Hgj1z0m: {
									"data-framer-name": "Variant 4",
								},
								YSJjBxE6e: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={140}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-1nfcth1-container"}
								data-framer-name={"1"}
								layoutDependency={layoutDependency}
								layoutId={"LWaj2Qom6-container"}
								name={"1"}
								nodeId={"LWaj2Qom6"}
								rendersWithMotion={true}
								scopeId={"v8UHvsoJG"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "LWaj2Qom6",
									layoutId: "LWaj2Qom6",
									name: "1",
									style: {
										width: "100%",
									},
									variant: matchVariant("lfpAgYSek"),
									width: "100%",
									YTCIaj6tN: "Do I need Claude Max?",
									zBMHYX5iv:
										"Nope. Claude Cowork is available for all paid plans, from the $20/month Pro plan to the $200/month Max plan. No matter what plan you're on, it's basically a full time digital employee. Even the cheapest virtual assistant costs between $500-$1000/month. You're getting that level of leverage for a fraction of the price. ",
									...addPropertyOverrides2(
										{
											CscMDZeaw: {
												fWTlhIRKu: fWTlhIRKuqipfw6,
												variant: matchVariant("HDQgyRxge"),
											},
											EYGZGvkqn: {
												fWTlhIRKu: fWTlhIRKuqipfw6,
												variant: matchVariant("HDQgyRxge"),
											},
											vIzlDr2lQ: {
												fWTlhIRKu: fWTlhIRKuqipfw6,
												variant: matchVariant("HDQgyRxge"),
											},
											w_Hgj1z0m: {
												fWTlhIRKu: fWTlhIRKuqipfw6,
												variant: matchVariant("HDQgyRxge"),
											},
											YSJjBxE6e: {
												fWTlhIRKu: fWTlhIRKuqipfw6,
												variant: matchVariant("HDQgyRxge"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={140}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 156}
						>
							<SmartComponentScopedContainer
								className={"framer-1t940sx-container"}
								data-framer-name={"2"}
								layoutDependency={layoutDependency}
								layoutId={"Z44BtgP5g-container"}
								name={"2"}
								nodeId={"Z44BtgP5g"}
								rendersWithMotion={true}
								scopeId={"v8UHvsoJG"}
							>
								{_jsx2(stdin_default, {
									fWTlhIRKu: fWTlhIRKu434jgf,
									height: "100%",
									id: "Z44BtgP5g",
									layoutId: "Z44BtgP5g",
									name: "2",
									style: {
										width: "100%",
									},
									variant: matchVariant("HDQgyRxge"),
									width: "100%",
									YTCIaj6tN: "Does this work on Windows?",
									zBMHYX5iv:
										"Yes! Cowork is available on both Mac and Windows Claude desktop applications. ",
									...addPropertyOverrides2(
										{
											YSJjBxE6e: {
												fWTlhIRKu: void 0,
												variant: matchVariant("lfpAgYSek"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={140}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 312}
						>
							<SmartComponentScopedContainer
								className={"framer-1sglpl6-container"}
								data-framer-name={"3"}
								layoutDependency={layoutDependency}
								layoutId={"oR6R612aK-container"}
								name={"3"}
								nodeId={"oR6R612aK"}
								rendersWithMotion={true}
								scopeId={"v8UHvsoJG"}
							>
								{_jsx2(stdin_default, {
									fWTlhIRKu: fWTlhIRKum44pyu,
									height: "100%",
									id: "oR6R612aK",
									layoutId: "oR6R612aK",
									name: "3",
									style: {
										width: "100%",
									},
									variant: matchVariant("HDQgyRxge"),
									width: "100%",
									YTCIaj6tN: "Is this self-paced or live?",
									zBMHYX5iv:
										"6 live sessions over 2 weeks + lifetime access to the session recordings, curriculum, and bonuses.",
									...addPropertyOverrides2(
										{
											CscMDZeaw: {
												fWTlhIRKu: void 0,
												variant: matchVariant("lfpAgYSek"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={140}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 468}
						>
							<SmartComponentScopedContainer
								className={"framer-1ivcopu-container"}
								data-framer-name={"4"}
								layoutDependency={layoutDependency}
								layoutId={"kz6c4pe1G-container"}
								name={"4"}
								nodeId={"kz6c4pe1G"}
								rendersWithMotion={true}
								scopeId={"v8UHvsoJG"}
							>
								{_jsx2(stdin_default, {
									fWTlhIRKu: fWTlhIRKue0d5q8,
									height: "100%",
									id: "kz6c4pe1G",
									layoutId: "kz6c4pe1G",
									name: "4",
									style: {
										width: "100%",
									},
									variant: matchVariant("HDQgyRxge"),
									width: "100%",
									YTCIaj6tN: "What commitment is required?",
									zBMHYX5iv:
										"Each live session is 60 minutes, and each .Skill should take about ~30 minutes to build along. It's structured for people with full-time jobs and kids, and it's likely that you earn back that time by letting AI take a weight off your shoulders.",
									...addPropertyOverrides2(
										{
											w_Hgj1z0m: {
												fWTlhIRKu: void 0,
												variant: matchVariant("lfpAgYSek"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={140}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 624}
						>
							<SmartComponentScopedContainer
								className={"framer-1ya9cwa-container"}
								data-framer-name={"5"}
								layoutDependency={layoutDependency}
								layoutId={"aSwrAWjzP-container"}
								name={"5"}
								nodeId={"aSwrAWjzP"}
								rendersWithMotion={true}
								scopeId={"v8UHvsoJG"}
							>
								{_jsx2(stdin_default, {
									fWTlhIRKu: fWTlhIRKu1hcwi60,
									height: "100%",
									id: "aSwrAWjzP",
									layoutId: "aSwrAWjzP",
									name: "5",
									style: {
										width: "100%",
									},
									variant: matchVariant("HDQgyRxge"),
									width: "100%",
									YTCIaj6tN: "What if I've never used AI before?",
									zBMHYX5iv:
										"Complete beginners are 100% welcome. No terminal. No API keys. No code. All we focus on is how to use the tools.",
									...addPropertyOverrides2(
										{
											vIzlDr2lQ: {
												fWTlhIRKu: void 0,
												variant: matchVariant("lfpAgYSek"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={140}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 780}
						>
							<SmartComponentScopedContainer
								className={"framer-1r5asnf-container"}
								data-framer-name={"6"}
								layoutDependency={layoutDependency}
								layoutId={"YU2AmMSvT-container"}
								name={"6"}
								nodeId={"YU2AmMSvT"}
								rendersWithMotion={true}
								scopeId={"v8UHvsoJG"}
							>
								{_jsx2(stdin_default, {
									fWTlhIRKu: fWTlhIRKulnq9nu,
									height: "100%",
									id: "YU2AmMSvT",
									layoutId: "YU2AmMSvT",
									name: "6",
									style: {
										width: "100%",
									},
									variant: matchVariant("HDQgyRxge"),
									width: "100%",
									YTCIaj6tN: "What about AI agents?",
									zBMHYX5iv:
										"Yes! Cowork is an agent. The fundamentals of AI agents are exactly what we're teaching you. Because of the pace of AI developments, learning how agents work is best done through the most up-to-date and user-friendly agent tool out there. This is how you learn Agents without learning how to code.",
									...addPropertyOverrides2(
										{
											EYGZGvkqn: {
												fWTlhIRKu: void 0,
												variant: matchVariant("lfpAgYSek"),
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8GVlV.framer-1b8lujb, .framer-8GVlV .framer-1b8lujb { display: block; }",
	".framer-8GVlV.framer-30jryl { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 736px; }",
	".framer-8GVlV .framer-1nfcth1-container, .framer-8GVlV .framer-1t940sx-container, .framer-8GVlV .framer-1sglpl6-container, .framer-8GVlV .framer-1ivcopu-container, .framer-8GVlV .framer-1ya9cwa-container, .framer-8GVlV .framer-1r5asnf-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var Framerv8UHvsoJG = withCSS2(Component2, css2, "framer-8GVlV");
var stdin_default2 = Framerv8UHvsoJG;
Framerv8UHvsoJG.displayName = "faq-main";
Framerv8UHvsoJG.defaultProps = {
	height: 668,
	width: 736,
};
addPropertyControls2(Framerv8UHvsoJG, {
	variant: {
		options: [
			"N6y2PsIAC",
			"YSJjBxE6e",
			"CscMDZeaw",
			"w_Hgj1z0m",
			"vIzlDr2lQ",
			"EYGZGvkqn",
		],
		optionTitles: [
			"Variant 1",
			"Variant 2",
			"Variant 3",
			"Variant 4",
			"Variant 5",
			"Variant 6",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	Framerv8UHvsoJG,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...FaqCompFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-main
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "N6y2PsIAC",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqMainFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_main_default = ComponentWithRoot;
export { faq_main_default as default };
