// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7f4cbde497b625c3 "Cowork Agent-Build", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-E76XYZGR.js";

// virtual:skill-maker-floppy
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rg5BFcSd569aGhgBLqlF/0yxOMTRox4DawosaSXqv/M6PCxD7ec.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-5vtRB";
var variantClassNames = {
	nN41jOzjO: "framer-v-q867a7",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "nN41jOzjO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-q867a7",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"nN41jOzjO"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 1024,
								intrinsicWidth: 1024,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 1024,
								pixelWidth: 1024,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/CNvjUIVXLGFBiE92dQRZNe5F6aM.png?width=1024&height=1024",
								srcSet:
									"https://framerusercontent.com/images/CNvjUIVXLGFBiE92dQRZNe5F6aM.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/CNvjUIVXLGFBiE92dQRZNe5F6aM.png?width=1024&height=1024 1024w",
							}}
							className={"framer-q09lle"}
							data-framer-name={"Skill-maker-skill"}
							layoutDependency={layoutDependency}
							layoutId={"RHrPnh1Pt"}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5vtRB.framer-f2s8f, .framer-5vtRB .framer-f2s8f { display: block; }",
	".framer-5vtRB.framer-q867a7 { height: 200px; position: relative; width: 200px; }",
	".framer-5vtRB .framer-q09lle { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
];
var FramerM6PCxD7ec = withCSS(Component, css, "framer-5vtRB");
var stdin_default = FramerM6PCxD7ec;
FramerM6PCxD7ec.displayName = "skill-maker-floppy";
FramerM6PCxD7ec.defaultProps = {
	height: 200,
	width: 200,
};
addFonts(
	FramerM6PCxD7ec,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:skill-maker-floppy
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SkillMakerFloppyFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var skill_maker_floppy_default = ComponentWithRoot;
export { skill_maker_floppy_default as default };
