// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 7f4cbde497b625c3 "Cowork Agent-Build", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * trackingPixelURL?: string // Tracking Pixel URL
}} Props

 */
import { routes } from "./chunks/chunk-E76XYZGR.js";

// virtual:thank-you
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ZzibP4wcxmS2c2K42lJw/iUrXw1L4PEnOVz1tSXR2/Thank_you.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
var C = {
	pageBg: "#0d1116",
	cardBg: "rgba(22, 27, 34, 0.6)",
	cardBorder: "rgba(243, 236, 203, 0.08)",
	cream: "#F3ECCB",
	creamSoft: "rgba(243, 236, 203, 0.7)",
	creamDim: "rgba(243, 236, 203, 0.65)",
	creamFaint: "rgba(243, 236, 203, 0.45)",
	creamGhost: "rgba(243, 236, 203, 0.12)",
	red: "#DB2624",
	yellow: "#FACC15",
	yellowSoft: "rgba(250, 204, 21, 0.1)",
	yellowBorder: "rgba(250, 204, 21, 0.2)",
	font: "'Manrope', Inter, system-ui, -apple-system, sans-serif",
};
function ThankYou({ width = 1440, trackingPixelUrl = "" }) {
	const mobile = width <= 390;
	const tablet = width > 390 && width <= 810;
	const mid = width > 810 && width <= 1200;
	const cardMaxWidth = mobile ? "100%" : tablet ? 520 : mid ? 580 : 620;
	const cardPadding = mobile
		? "32px 20px"
		: tablet
			? "40px 32px"
			: mid
				? "48px 40px"
				: "56px 48px";
	const h1Size = mobile ? 24 : tablet ? 28 : mid ? 32 : 36;
	const subtitleSize = mobile ? 15 : tablet ? 16 : mid ? 17 : 18;
	const h2Size = mobile ? 18 : tablet ? 19 : mid ? 20 : 22;
	const bodySize = mobile ? 14 : tablet ? 15 : 16;
	const emailSize = mobile ? 13 : tablet ? 14 : 15;
	const badgeMargin = mobile ? 20 : tablet ? 24 : 32;
	const subtitleMargin = mobile ? 24 : tablet ? 28 : mid ? 32 : 40;
	const dividerMargin = mobile ? 24 : tablet ? 28 : mid ? 32 : 40;
	const instructionsMargin = mobile ? 20 : tablet ? 24 : 32;
	const glowSize = mobile ? 350 : tablet ? 500 : mid ? 700 : 900;
	const wrapperPadding = mobile
		? "32px 16px"
		: tablet
			? "48px 20px"
			: mid
				? "60px 24px"
				: "80px 24px";
	return (
		<div
			style={{
				width: "100%",
				minHeight: "100vh",
				display: "flex",
				flexDirection: "column",
				alignItems: "center",
				justifyContent: "center",
				padding: wrapperPadding,
				position: "relative",
				overflow: "hidden",
				background: C.pageBg,
				fontFamily: C.font,
				color: C.cream,
			}}
		>
			<div
				style={{
					position: "absolute",
					top: "50%",
					left: "50%",
					transform: "translate(-50%, -50%)",
					width: glowSize,
					height: glowSize,
					background: `radial-gradient(circle, rgba(219, 38, 36, 0.08) 0%, transparent 70%)`,
					pointerEvents: "none",
				}}
			/>
			<div
				style={{
					position: "relative",
					maxWidth: cardMaxWidth,
					width: "100%",
					background: C.cardBg,
					border: `1px solid ${C.cardBorder}`,
					borderRadius: mobile ? 14 : tablet ? 16 : 20,
					padding: cardPadding,
					backdropFilter: "blur(12px)",
					textAlign: "center",
				}}
			>
				<div
					style={{
						position: "absolute",
						top: 0,
						left: "50%",
						transform: "translateX(-50%)",
						width: mobile ? 60 : 80,
						height: 3,
						background: `linear-gradient(90deg, ${C.red}, ${C.yellow})`,
						borderRadius: "0 0 3px 3px",
					}}
				/>
				<div
					style={{
						display: "inline-block",
						fontSize: mobile ? 10 : 11,
						fontWeight: 700,
						textTransform: "uppercase",
						letterSpacing: "0.15em",
						color: C.yellow,
						background: C.yellowSoft,
						border: `1px solid ${C.yellowBorder}`,
						padding: mobile ? "5px 12px" : "6px 16px",
						borderRadius: 100,
						marginBottom: badgeMargin,
					}}
				>
					{"You're In"}
				</div>
				<h1
					style={{
						fontSize: h1Size,
						fontWeight: 800,
						lineHeight: 1.2,
						letterSpacing: mobile ? -0.3 : -0.5,
						marginBottom: 12,
						color: C.cream,
					}}
				>
					{"Welcome to Claude"}
					<br />
					{"Cowork "}
					<span
						style={{
							color: C.yellow,
						}}
					>
						{"Bootcamp!"}
					</span>
				</h1>
				<p
					style={{
						fontSize: subtitleSize,
						fontWeight: 500,
						color: C.creamSoft,
						lineHeight: mobile ? 1.5 : 1.6,
						marginBottom: subtitleMargin,
					}}
				>
					{"You're now one step closer to building"}{" "}
					<span
						style={{
							fontWeight: 800,
							color: C.cream,
						}}
					>
						{".Skills"}
					</span>{" "}
					{"that work for you forever."}
				</p>
				<div
					style={{
						width: mobile ? 32 : 40,
						height: 1,
						background: C.creamGhost,
						margin: `0 auto ${dividerMargin}px`,
					}}
				/>
				<h2
					style={{
						fontSize: h2Size,
						fontWeight: 700,
						marginBottom: mobile ? 14 : 20,
						letterSpacing: -0.3,
						color: C.cream,
					}}
				>
					{"Now, let's get you set up."}
				</h2>
				<div
					style={{
						textAlign: "left",
						marginBottom: instructionsMargin,
					}}
				>
					<p
						style={{
							fontSize: bodySize,
							fontWeight: 500,
							color: C.creamDim,
							lineHeight: mobile ? 1.6 : 1.7,
							marginBottom: 16,
						}}
					>
						{
							"A few moments ago, you should've received an email with the subject line:"
						}
					</p>
					<div
						style={{
							display: "inline-flex",
							alignItems: "center",
							gap: mobile ? 6 : 8,
							background: "rgba(243, 236, 203, 0.06)",
							border: "1px solid rgba(243, 236, 203, 0.1)",
							borderRadius: mobile ? 8 : 10,
							padding: mobile
								? "12px 14px"
								: tablet
									? "12px 16px"
									: "14px 20px",
							fontSize: emailSize,
							fontWeight: 700,
							color: C.cream,
							margin: "4px 0 16px",
							width: "100%",
							justifyContent: "center",
						}}
					>
						<span
							style={{
								fontSize: mobile ? 16 : 18,
							}}
						>
							{"\u{1F916}"}
						</span>
						<span>{"[IMPORTANT] Welcome to Claude Cowork Bootcamp"}</span>
					</div>
					<p
						style={{
							fontSize: bodySize,
							fontWeight: 500,
							color: C.creamDim,
							lineHeight: mobile ? 1.6 : 1.7,
							marginBottom: 16,
						}}
					>
						{
							"Inside, you'll find your onboarding link and next steps to help you get up to speed\u2014so you can hit the ground running when Session 1 kicks off on"
						}{" "}
						<strong
							style={{
								color: C.cream,
							}}
						>
							{"February 23rd"}
						</strong>
						{"."}
					</p>
				</div>
				<p
					style={{
						fontSize: mobile ? 14 : 15,
						fontWeight: 500,
						color: C.creamFaint,
						lineHeight: 1.6,
					}}
				>
					{"See you inside,"}
					<span
						style={{
							display: "block",
							marginTop: 4,
							fontWeight: 700,
							color: C.creamDim,
						}}
					>
						{"Cole, Dickie & Mitch"}
					</span>
				</p>
			</div>
			{trackingPixelUrl && (
				<img
					src={trackingPixelUrl}
					width={1}
					height={1}
					style={{
						position: "absolute",
						opacity: 0,
					}}
					alt={""}
				/>
			)}
		</div>
	);
}
addPropertyControls(ThankYou, {
	trackingPixelUrl: {
		type: ControlType.String,
		title: "Tracking Pixel URL",
		defaultValue: "",
		description: "Affiliate tracking pixel image URL",
	},
});

// virtual:thank-you
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			<ThankYou {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ThankYouFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"7f4cbde497b625c3b904bd16e22935f24d0af77b40924d86d0a6cffa84999740"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={ThankYou}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, ThankYou);
var thank_you_default = ComponentWithRoot;
export { thank_you_default as default };
